export type Product = {
  id: number;
  category: string;
  productName: string;
  packingSize: string;
  uom: string;
};

let _id = 0;
const P = (category: string, productName: string, packingSize: string, uom: string): Product => ({
  id: ++_id,
  category,
  productName,
  packingSize,
  uom,
});

export const PRODUCT_CATALOG: Product[] = [
  // ── BOXES ──────────────────────────────────────────────────────────────────
  P("Boxes", "Boxes - Bvg Agro Safe", "200 ml", "ml"),
  P("Boxes", "Boxes - Bvg Agro Safe", "400 ml", "ml"),
  P("Boxes", "Boxes - Bvg Agro Safe", "1000 ml", "ml"),
  P("Boxes", "Boxes - Bvg Agro Safe", "5000 ml", "ml"),
  P("Boxes", "Boxes - Bvg Agrow Magic", "200 ml", "ml"),
  P("Boxes", "Boxes - Bvg Agrow Magic", "400 ml", "ml"),
  P("Boxes", "Boxes - Bvg Agrow Magic", "1000 ml", "ml"),
  P("Boxes", "Boxes - Bvg Agrow Magic", "5000 ml", "ml"),
  P("Boxes", "Boxes - Bvg Agro Nutri", "100 gm", "gm"),
  P("Boxes", "Boxes - Bvg Agro Nutri", "250 gm", "gm"),
  P("Boxes", "Boxes - Bvg Agro Nutri", "500 gm", "gm"),
  P("Boxes", "Boxes - Bvg Carbon Plus", "1000 ml", "ml"),
  P("Boxes", "Boxes - Bvg Carbon Plus", "5000 ml", "ml"),
  P("Boxes", "Boxes - Bvg Synergy", "100 gm", "gm"),
  P("Boxes", "Boxes - Bvg Synergy", "250 gm", "gm"),
  P("Boxes", "Boxes - Bvg Synergy", "500 gm", "gm"),
  P("Boxes", "Boxes - Bvg Root Care", "1000 ml", "ml"),
  P("Boxes", "Boxes - Bvg Root Care", "2000 ml", "ml"),
  P("Boxes", "Boxes - Bvg Pollinator", "250 ml", "ml"),
  P("Boxes", "Boxes - Bvg Pollinator", "500 ml", "ml"),
  P("Boxes", "Boxes - Bvg Pollinator", "1000 ml", "ml"),
  P("Boxes", "Boxes - Bvg Gold", "250 ml", "ml"),
  P("Boxes", "Boxes - Bvg Gold", "500 ml", "ml"),
  P("Boxes", "Boxes - Bvg Gold", "1000 ml", "ml"),
  P("Boxes", "Boxes - Bvg Masterstroke", "250 ml", "ml"),
  P("Boxes", "Boxes - Bvg Masterstroke", "500 ml", "ml"),
  P("Boxes", "Boxes - Bvg Masterstroke", "1000 ml", "ml"),
  P("Boxes", "Boxes - Bvg CalBoost +", "250 gm", "gm"),
  P("Boxes", "Boxes - Bvg CalBoost +", "500 gm", "gm"),
  P("Boxes", "Boxes - Bvg Stickwet", "50 ml", "ml"),
  P("Boxes", "Boxes - Bvg Stickwet", "100 ml", "ml"),
  P("Boxes", "Boxes - Bvg Stickwet", "250 ml", "ml"),
  P("Boxes", "Boxes - Bvg Stickwet", "500 ml", "ml"),
  P("Boxes", "Boxes - Bvg Balancer", "100 ml", "ml"),
  P("Boxes", "Boxes - Bvg Balancer", "250 ml", "ml"),
  P("Boxes", "Boxes - Bvg Balancer", "500 ml", "ml"),
  P("Boxes", "Boxes - Bvg Balancer", "1000 ml", "ml"),

  // ── STICKERS ────────────────────────────────────────────────────────────────
  P("Stickers", "Stickers - Bvg Agro Safe", "200 ml", "ml"),
  P("Stickers", "Stickers - Bvg Agro Safe", "400 ml", "ml"),
  P("Stickers", "Stickers - Bvg Agro Safe", "1000 ml", "ml"),
  P("Stickers", "Stickers - Bvg Agro Safe", "5000 Front", "nos"),
  P("Stickers", "Stickers - Bvg Agro Safe", "5000 Back", "nos"),
  P("Stickers", "Stickers - Bvg Agrow Magic", "100 ml", "ml"),
  P("Stickers", "Stickers - Bvg Agrow Magic", "200 ml", "ml"),
  P("Stickers", "Stickers - Bvg Agrow Magic", "400 ml", "ml"),
  P("Stickers", "Stickers - Bvg Agrow Magic", "1000 ml", "ml"),
  P("Stickers", "Stickers - Bvg Agrow Magic", "5000 Front", "nos"),
  P("Stickers", "Stickers - Bvg Agrow Magic", "5000 Back", "nos"),
  P("Stickers", "Stickers - Bvg Agro Nutri", "100 gm", "gm"),
  P("Stickers", "Stickers - Bvg Agro Nutri", "250 gm", "gm"),
  P("Stickers", "Stickers - Bvg Agro Nutri", "500 gm", "gm"),
  P("Stickers", "Stickers - Bvg Synergy", "250 gm", "gm"),
  P("Stickers", "Stickers - Bvg Synergy", "500 gm", "gm"),
  P("Stickers", "Stickers - Bvg Synergy", "1 kg", "kg"),
  P("Stickers", "Stickers - Bvg Synergy", "5 kg", "kg"),
  P("Stickers", "Stickers - Bvg Carbon Plus", "500 ml", "ml"),
  P("Stickers", "Stickers - Bvg Carbon Plus", "1000 ml", "ml"),
  P("Stickers", "Stickers - Bvg Carbon Plus", "5000 Front", "nos"),
  P("Stickers", "Stickers - Bvg Carbon Plus", "5000 Back", "nos"),
  P("Stickers", "Stickers - Bvg Root Care", "1000 ml", "ml"),
  P("Stickers", "Stickers - Bvg Root Care", "2000 ml", "ml"),
  P("Stickers", "Stickers - Bvg Calboost +", "250 gm", "gm"),
  P("Stickers", "Stickers - Bvg Calboost +", "500 gm", "gm"),
  P("Stickers", "Stickers - Bvg Gold", "250 ml", "ml"),
  P("Stickers", "Stickers - Bvg Gold", "500 ml", "ml"),
  P("Stickers", "Stickers - Bvg Gold", "1000 ml", "ml"),
  P("Stickers", "Stickers - Bvg Masterstroke", "250 ml", "ml"),
  P("Stickers", "Stickers - Bvg Masterstroke", "500 ml", "ml"),
  P("Stickers", "Stickers - Bvg Masterstroke", "1000 ml", "ml"),
  P("Stickers", "Stickers - Bvg Pollinator", "250 ml", "ml"),
  P("Stickers", "Stickers - Bvg Pollinator", "500 ml", "ml"),
  P("Stickers", "Stickers - Bvg Pollinator", "1000 ml", "ml"),
  P("Stickers", "Stickers - Bvg Balancer", "100 ml", "ml"),
  P("Stickers", "Stickers - Bvg Balancer", "250 ml", "ml"),
  P("Stickers", "Stickers - Bvg Balancer", "500 ml", "ml"),
  P("Stickers", "Stickers - Bvg Balancer", "1000 ml", "ml"),
  P("Stickers", "Stickers - Bvg Stickwet", "50 ml", "ml"),
  P("Stickers", "Stickers - Bvg Stickwet", "100 ml", "ml"),
  P("Stickers", "Stickers - Bvg Stickwet", "250 ml", "ml"),
  P("Stickers", "Stickers - Bvg Stickwet", "500 ml", "ml"),
  P("Stickers", "Stickers - Bvg Stickwet", "1000 ml", "ml"),
  P("Stickers", "Sticker - Bvg Chelated Mix", "250 gm", "gm"),
  P("Stickers", "Sticker - Bvg Chelated Mix", "500 gm", "gm"),
  P("Stickers", "Sticker - Bvg Chelated Zinc", "250 gm", "gm"),
  P("Stickers", "Stickers - Bvg Silspray", "500 ml", "ml"),

  // ── EMPTY BOTTLES ──────────────────────────────────────────────────────────
  P("Empty Bottles", "Empty Bottles", "50 Round", "nos"),
  P("Empty Bottles", "Empty Bottles", "50 Square", "nos"),
  P("Empty Bottles", "Empty Bottles", "100 Round", "nos"),
  P("Empty Bottles", "Empty Bottles", "100 Square", "nos"),
  P("Empty Bottles", "Empty Bottles", "250 Square", "nos"),
  P("Empty Bottles", "Empty Bottles", "250 Round", "nos"),
  P("Empty Bottles", "Empty Bottles", "500 Round", "nos"),
  P("Empty Bottles", "Empty Bottles", "500 Square", "nos"),
  P("Empty Bottles", "Empty Bottles", "1000 Round", "nos"),
  P("Empty Bottles", "Empty Bottles", "2000 Round", "nos"),
  P("Empty Bottles", "Empty Bottles", "5000", "nos"),

  // ── BVG PRODUCTS ────────────────────────────────────────────────────────────
  P("BVG Products", "Bvg Agro Safe", "50", "ml"),
  P("BVG Products", "Bvg Agro Safe", "100", "ml"),
  P("BVG Products", "Bvg Agro Safe", "200", "ml"),
  P("BVG Products", "Bvg Agro Safe", "400", "ml"),
  P("BVG Products", "Bvg Agro Safe", "1000", "ml"),
  P("BVG Products", "Bvg Agro Safe", "5000", "ml"),
  P("BVG Products", "Bvg Agrow Magic", "50", "ml"),
  P("BVG Products", "Bvg Agrow Magic", "100", "ml"),
  P("BVG Products", "Bvg Agrow Magic", "200", "ml"),
  P("BVG Products", "Bvg Agrow Magic", "400", "ml"),
  P("BVG Products", "Bvg Agrow Magic", "1000", "ml"),
  P("BVG Products", "Bvg Agrow Magic", "5000", "ml"),
  P("BVG Products", "Bvg Agro Nutri", "50", "ml"),
  P("BVG Products", "Bvg Agro Nutri", "100", "ml"),
  P("BVG Products", "Bvg Agro Nutri", "250", "ml"),
  P("BVG Products", "Bvg Agro Nutri", "500", "ml"),
  P("BVG Products", "Bvg Agro Nutri", "1000", "ml"),
  P("BVG Products", "Bvg Synergy", "100", "ml"),
  P("BVG Products", "Bvg Synergy", "250", "ml"),
  P("BVG Products", "Bvg Synergy", "500", "ml"),
  P("BVG Products", "Bvg Synergy", "1000", "ml"),
  P("BVG Products", "Bvg Synergy", "5000", "ml"),
  P("BVG Products", "Bvg Carbon Plus", "500", "ml"),
  P("BVG Products", "Bvg Carbon Plus", "1000", "ml"),
  P("BVG Products", "Bvg Carbon Plus", "2000", "ml"),
  P("BVG Products", "Bvg Carbon Plus", "5000", "ml"),
  P("BVG Products", "Bvg Root Care", "250", "ml"),
  P("BVG Products", "Bvg Root Care", "500", "ml"),
  P("BVG Products", "Bvg Root Care", "1000", "ml"),
  P("BVG Products", "Bvg Root Care", "2000", "ml"),
  P("BVG Products", "Bvg Calboost Plus", "250", "ml"),
  P("BVG Products", "Bvg Calboost Plus", "500", "ml"),
  P("BVG Products", "Bvg Calboost Plus", "1000", "ml"),
  P("BVG Products", "Bvg Calboost Plus", "5000", "ml"),
  P("BVG Products", "Bvg Gold", "250", "ml"),
  P("BVG Products", "Bvg Gold", "500", "ml"),
  P("BVG Products", "Bvg Gold", "1000", "ml"),
  P("BVG Products", "Bvg Masterstroke", "250", "ml"),
  P("BVG Products", "Bvg Masterstroke", "500", "ml"),
  P("BVG Products", "Bvg Masterstroke", "1000", "ml"),
  P("BVG Products", "Bvg Pollinator", "250", "ml"),
  P("BVG Products", "Bvg Pollinator", "500", "ml"),
  P("BVG Products", "Bvg Pollinator", "1000", "ml"),
  P("BVG Products", "Bvg Balancer", "100", "ml"),
  P("BVG Products", "Bvg Balancer", "250", "ml"),
  P("BVG Products", "Bvg Balancer", "500", "ml"),
  P("BVG Products", "Bvg Balancer", "1000", "ml"),
  P("BVG Products", "Bvg Stickwet", "50", "ml"),
  P("BVG Products", "Bvg Stickwet", "100", "ml"),
  P("BVG Products", "Bvg Stickwet", "250", "ml"),
  P("BVG Products", "Bvg Stickwet", "500", "ml"),
  P("BVG Products", "Bvg Stickwet", "1000", "ml"),
  P("BVG Products", "Bvg Chelated", "250", "gm"),
  P("BVG Products", "Bvg Chelated", "500", "gm"),
  P("BVG Products", "Bvg Chelated", "250", "gm"),
  P("BVG Products", "Bvg Carbon Gr.", "10", "kg"),
  P("BVG Products", "Bvg Carbon Gr.", "20", "kg"),
  P("BVG Products", "Bvg Prom Pw.", "1", "kg"),
  P("BVG Products", "Bvg Prom", "50", "nos"),
  P("BVG Products", "Bvg Potash", "50", "nos"),
  P("BVG Products", "Bvg Silicon", "50", "nos"),
  P("BVG Products", "Bvg Sanjeevani Pw.", "1", "kg"),
  P("BVG Products", "Bvg Sanjeevani", "50", "ml"),
  P("BVG Products", "Bvg Vardaan", "1.5", "kg"),
  P("BVG Products", "Bvg Rajjo", "600", "ml"),
  P("BVG Products", "Bvg Dhara", "150", "ml"),
  P("BVG Products", "Bvg Jalsudhar Plus (In Inches)", "3", "nos"),
  P("BVG Products", "Bvg Solar Light Trap", "1", "nos"),
  P("BVG Products", "Bvg Petrol Operated Spray Pump", "1", "nos"),
  P("BVG Products", "Bvg Krushi Tantradnyan Book", "Marathi", "nos"),
  P("BVG Products", "Bvg Krushi Tantradnyan Book", "Hindi", "nos"),
  P("BVG Products", "Bvg Krushi Tantradnyan Book", "English", "nos"),
  P("BVG Products", "Bvg Agrosil Silica", "200", "gm"),
  P("BVG Products", "Bvg Agrosil Silica", "40", "kg"),
  P("BVG Products", "Bvg Mobile Auto Pro - Basic", "1", "nos"),
  P("BVG Products", "Bvg Mobile Auto Pro - With Battery", "1", "nos"),
  P("BVG Products", "Bvg Dry Run Auto", "1", "nos"),
  P("BVG Products", "Bvg Silspray (TTSC)", "1000", "ml"),

  // ── RAW MATERIAL ───────────────────────────────────────────────────────────
  P("Raw Material", "Bvg Agro Safe DRUM", "200 Ltr", "drum"),
  P("Raw Material", "Bvg Synergy (Lithovit Standard) BAG", "1000 Kg", "bag"),
  P("Raw Material", "Bvg CalBoost + (Lithovit Boron 05) BAG", "1000 Kg", "bag"),
  P("Raw Material", "Bvg Balancer Drum", "200 Ltr", "drum"),
  P("Raw Material", "Bvg Stickwet Drum", "200 Ltr", "drum"),
  P("Raw Material", "Bvg Root Care", "1", "nos"),
  P("Raw Material", "Bvg Vardaan BAG", "25 Kg", "bag"),
  P("Raw Material", "Bvg Rajjo BAG", "25 Kg", "bag"),
  P("Raw Material", "Bvg Dhara", "1", "nos"),
  P("Raw Material", "Bvg Sanjeevani", "1", "nos"),
  P("Raw Material", "Bvg Carbon Gr.", "1", "nos"),
  P("Raw Material", "Biocoal Briquettes", "1", "nos"),

  // ── CONSUMABLES - EMPTY BAGS & POUCHES ─────────────────────────────────────
  P("Consumables - Empty Bags & Pouches", "Empty Bags - Prom Pw.", "50 kg", "bag"),
  P("Consumables - Empty Bags & Pouches", "Empty Bags - Prom Gr.", "50 kg", "bag"),
  P("Consumables - Empty Bags & Pouches", "Empty Bags - Potash", "50 kg", "bag"),
  P("Consumables - Empty Bags & Pouches", "Empty Bags - Silicon", "50 Kg", "bag"),
  P("Consumables - Empty Bags & Pouches", "Empty Bags - Sanjeevani Pw.", "50 kg", "bag"),
  P("Consumables - Empty Bags & Pouches", "Empty Bags - Carbon Gr.", "10 kg", "bag"),
  P("Consumables - Empty Bags & Pouches", "Empty Bags - Carbon Gr.", "20 kg", "bag"),
  P("Consumables - Empty Bags & Pouches", "Sanjeevani Pouch", "1 Kg", "pouch"),
  P("Consumables - Empty Bags & Pouches", "Prom Pw. Pouch", "1 Kg", "pouch"),
  P("Consumables - Empty Bags & Pouches", "Synergy Pouch", "100 gm", "pouch"),
  P("Consumables - Empty Bags & Pouches", "Synergy Pouch", "250 gm", "pouch"),
  P("Consumables - Empty Bags & Pouches", "Synergy Pouch", "500 gm", "pouch"),
  P("Consumables - Empty Bags & Pouches", "Calboost Pouch", "250 GM", "pouch"),
  P("Consumables - Empty Bags & Pouches", "Calboost Pouch", "500 GM", "pouch"),
  P("Consumables - Empty Bags & Pouches", "Vardan Pouches", "1.5 Kg", "pouch"),
  P("Consumables - Empty Bags & Pouches", "Rajjo Pouches", "300 GM", "pouch"),
  P("Consumables - Empty Bags & Pouches", "Rajjo Pouches", "600 GM", "pouch"),
  P("Consumables - Empty Bags & Pouches", "Cello Tape", "1", "roll"),
  P("Consumables - Empty Bags & Pouches", "PVC Packing Patti (Straping Roll)", "1", "roll"),
];
