import { db } from "@/db";
import { products } from "@/db/schema";

// All products from the provided images
const ALL_PRODUCTS = [
  // ── BOXES ──────────────────────────────────────────────────────────────────
  { category: "Boxes", productName: "Boxes - Bvg Agro Safe",        packingSize: "200 ml",  uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Agro Safe",        packingSize: "400 ml",  uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Agro Safe",        packingSize: "1000 ml", uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Agro Safe",        packingSize: "5000 ml", uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Agrow Magic",      packingSize: "200 ml",  uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Agrow Magic",      packingSize: "400 ml",  uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Agrow Magic",      packingSize: "1000 ml", uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Agrow Magic",      packingSize: "5000 ml", uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Agro Nutri",       packingSize: "100 gm",  uom: "gm" },
  { category: "Boxes", productName: "Boxes - Bvg Agro Nutri",       packingSize: "250 gm",  uom: "gm" },
  { category: "Boxes", productName: "Boxes - Bvg Agro Nutri",       packingSize: "500 gm",  uom: "gm" },
  { category: "Boxes", productName: "Boxes - Bvg Carbon Plus",      packingSize: "1000 ml", uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Carbon Plus",      packingSize: "5000 ml", uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Synergy",          packingSize: "100 gm",  uom: "gm" },
  { category: "Boxes", productName: "Boxes - Bvg Synergy",          packingSize: "250 gm",  uom: "gm" },
  { category: "Boxes", productName: "Boxes - Bvg Synergy",          packingSize: "500 gm",  uom: "gm" },
  { category: "Boxes", productName: "Boxes - Bvg Root Care",        packingSize: "1000 ml", uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Root Care",        packingSize: "2000 ml", uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Pollinator",       packingSize: "250 ml",  uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Pollinator",       packingSize: "500 ml",  uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Pollinator",       packingSize: "1000 ml", uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Gold",             packingSize: "250 ml",  uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Gold",             packingSize: "500 ml",  uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Gold",             packingSize: "1000 ml", uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Masterstroke",     packingSize: "250 ml",  uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Masterstroke",     packingSize: "500 ml",  uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Masterstroke",     packingSize: "1000 ml", uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg CalBoost +",       packingSize: "250 gm",  uom: "gm" },
  { category: "Boxes", productName: "Boxes - Bvg CalBoost +",       packingSize: "500 gm",  uom: "gm" },
  { category: "Boxes", productName: "Boxes - Bvg Stickwet",         packingSize: "50 ml",   uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Stickwet",         packingSize: "100 ml",  uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Stickwet",         packingSize: "250 ml",  uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Stickwet",         packingSize: "500 ml",  uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Balancer",         packingSize: "100 ml",  uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Balancer",         packingSize: "250 ml",  uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Balancer",         packingSize: "500 ml",  uom: "ml" },
  { category: "Boxes", productName: "Boxes - Bvg Balancer",         packingSize: "1000 ml", uom: "ml" },

  // ── STICKERS ────────────────────────────────────────────────────────────────
  { category: "Stickers", productName: "Stickers - Bvg Agro Safe",     packingSize: "200 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Agro Safe",     packingSize: "400 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Agro Safe",     packingSize: "1000 ml",    uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Agro Safe",     packingSize: "5000 Front",  uom: "nos" },
  { category: "Stickers", productName: "Stickers - Bvg Agro Safe",     packingSize: "5000 Back",   uom: "nos" },
  { category: "Stickers", productName: "Stickers - Bvg Agrow Magic",   packingSize: "100 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Agrow Magic",   packingSize: "200 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Agrow Magic",   packingSize: "400 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Agrow Magic",   packingSize: "1000 ml",    uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Agrow Magic",   packingSize: "5000 Front",  uom: "nos" },
  { category: "Stickers", productName: "Stickers - Bvg Agrow Magic",   packingSize: "5000 Back",   uom: "nos" },
  { category: "Stickers", productName: "Stickers - Bvg Agro Nutri",    packingSize: "100 gm",     uom: "gm" },
  { category: "Stickers", productName: "Stickers - Bvg Agro Nutri",    packingSize: "250 gm",     uom: "gm" },
  { category: "Stickers", productName: "Stickers - Bvg Agro Nutri",    packingSize: "500 gm",     uom: "gm" },
  { category: "Stickers", productName: "Stickers - Bvg Synergy",       packingSize: "250 gm",     uom: "gm" },
  { category: "Stickers", productName: "Stickers - Bvg Synergy",       packingSize: "500 gm",     uom: "gm" },
  { category: "Stickers", productName: "Stickers - Bvg Synergy",       packingSize: "1 kg",       uom: "kg" },
  { category: "Stickers", productName: "Stickers - Bvg Synergy",       packingSize: "5 kg",       uom: "kg" },
  { category: "Stickers", productName: "Stickers - Bvg Carbon Plus",   packingSize: "500 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Carbon Plus",   packingSize: "1000 ml",    uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Carbon Plus",   packingSize: "5000 Front",  uom: "nos" },
  { category: "Stickers", productName: "Stickers - Bvg Carbon Plus",   packingSize: "5000 Back",   uom: "nos" },
  { category: "Stickers", productName: "Stickers - Bvg Root Care",     packingSize: "1000 ml",    uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Root Care",     packingSize: "2000 ml",    uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Calboost +",    packingSize: "250 gm",     uom: "gm" },
  { category: "Stickers", productName: "Stickers - Bvg Calboost +",    packingSize: "500 gm",     uom: "gm" },
  { category: "Stickers", productName: "Stickers - Bvg Gold",          packingSize: "250 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Gold",          packingSize: "500 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Gold",          packingSize: "1000 ml",    uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Masterstroke",  packingSize: "250 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Masterstroke",  packingSize: "500 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Masterstroke",  packingSize: "1000 ml",    uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Pollinator",    packingSize: "250 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Pollinator",    packingSize: "500 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Pollinator",    packingSize: "1000 ml",    uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Balancer",      packingSize: "100 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Balancer",      packingSize: "250 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Balancer",      packingSize: "500 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Balancer",      packingSize: "1000 ml",    uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Stickwet",      packingSize: "50 ml",      uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Stickwet",      packingSize: "100 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Stickwet",      packingSize: "250 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Stickwet",      packingSize: "500 ml",     uom: "ml" },
  { category: "Stickers", productName: "Stickers - Bvg Stickwet",      packingSize: "1000 ml",    uom: "ml" },
  { category: "Stickers", productName: "Sticker - Bvg Chelated Mix",   packingSize: "250 gm",     uom: "gm" },
  { category: "Stickers", productName: "Sticker - Bvg Chelated Mix",   packingSize: "500 gm",     uom: "gm" },
  { category: "Stickers", productName: "Sticker - Bvg Chelated Zinc",  packingSize: "250 gm",     uom: "gm" },
  { category: "Stickers", productName: "Stickers - Bvg Silspray",      packingSize: "500 ml",     uom: "ml" },

  // ── EMPTY BOTTLES ──────────────────────────────────────────────────────────
  { category: "Empty Bottles", productName: "Empty Bottles", packingSize: "50 Round",    uom: "nos" },
  { category: "Empty Bottles", productName: "Empty Bottles", packingSize: "50 Square",   uom: "nos" },
  { category: "Empty Bottles", productName: "Empty Bottles", packingSize: "100 Round",   uom: "nos" },
  { category: "Empty Bottles", productName: "Empty Bottles", packingSize: "100 Square",  uom: "nos" },
  { category: "Empty Bottles", productName: "Empty Bottles", packingSize: "250 Square",  uom: "nos" },
  { category: "Empty Bottles", productName: "Empty Bottles", packingSize: "250 Round",   uom: "nos" },
  { category: "Empty Bottles", productName: "Empty Bottles", packingSize: "500 Round",   uom: "nos" },
  { category: "Empty Bottles", productName: "Empty Bottles", packingSize: "500 Square",  uom: "nos" },
  { category: "Empty Bottles", productName: "Empty Bottles", packingSize: "1000 Round",  uom: "nos" },
  { category: "Empty Bottles", productName: "Empty Bottles", packingSize: "2000 Round",  uom: "nos" },
  { category: "Empty Bottles", productName: "Empty Bottles", packingSize: "5000",        uom: "nos" },

  // ── BVG PRODUCTS ────────────────────────────────────────────────────────────
  { category: "BVG Products", productName: "Bvg Agro Safe",              packingSize: "50",       uom: "ml" },
  { category: "BVG Products", productName: "Bvg Agro Safe",              packingSize: "100",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Agro Safe",              packingSize: "200",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Agro Safe",              packingSize: "400",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Agro Safe",              packingSize: "1000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Agro Safe",              packingSize: "5000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Agrow Magic",            packingSize: "50",       uom: "ml" },
  { category: "BVG Products", productName: "Bvg Agrow Magic",            packingSize: "100",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Agrow Magic",            packingSize: "200",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Agrow Magic",            packingSize: "400",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Agrow Magic",            packingSize: "1000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Agrow Magic",            packingSize: "5000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Agro Nutri",             packingSize: "50",       uom: "ml" },
  { category: "BVG Products", productName: "Bvg Agro Nutri",             packingSize: "100",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Agro Nutri",             packingSize: "250",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Agro Nutri",             packingSize: "500",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Agro Nutri",             packingSize: "1000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Synergy",                packingSize: "100",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Synergy",                packingSize: "250",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Synergy",                packingSize: "500",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Synergy",                packingSize: "1000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Synergy",                packingSize: "5000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Carbon Plus",            packingSize: "500",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Carbon Plus",            packingSize: "1000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Carbon Plus",            packingSize: "2000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Carbon Plus",            packingSize: "5000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Root Care",              packingSize: "250",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Root Care",              packingSize: "500",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Root Care",              packingSize: "1000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Root Care",              packingSize: "2000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Calboost Plus",          packingSize: "250",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Calboost Plus",          packingSize: "500",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Calboost Plus",          packingSize: "1000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Calboost Plus",          packingSize: "5000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Gold",                   packingSize: "250",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Gold",                   packingSize: "500",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Gold",                   packingSize: "1000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Masterstroke",           packingSize: "250",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Masterstroke",           packingSize: "500",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Masterstroke",           packingSize: "1000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Pollinator",             packingSize: "250",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Pollinator",             packingSize: "500",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Pollinator",             packingSize: "1000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Balancer",               packingSize: "100",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Balancer",               packingSize: "250",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Balancer",               packingSize: "500",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Balancer",               packingSize: "1000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Stickwet",               packingSize: "50",       uom: "ml" },
  { category: "BVG Products", productName: "Bvg Stickwet",               packingSize: "100",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Stickwet",               packingSize: "250",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Stickwet",               packingSize: "500",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Stickwet",               packingSize: "1000",     uom: "ml" },
  { category: "BVG Products", productName: "Bvg Chelated",               packingSize: "250",      uom: "gm" },
  { category: "BVG Products", productName: "Bvg Chelated",               packingSize: "500",      uom: "gm" },
  { category: "BVG Products", productName: "Bvg Chelated",               packingSize: "250",      uom: "gm" },
  { category: "BVG Products", productName: "Bvg Carbon Gr.",             packingSize: "10",       uom: "kg" },
  { category: "BVG Products", productName: "Bvg Carbon Gr.",             packingSize: "20",       uom: "kg" },
  { category: "BVG Products", productName: "Bvg Prom Pw.",               packingSize: "1",        uom: "kg" },
  { category: "BVG Products", productName: "Bvg Prom",                   packingSize: "50",       uom: "nos" },
  { category: "BVG Products", productName: "Bvg Potash",                 packingSize: "50",       uom: "nos" },
  { category: "BVG Products", productName: "Bvg Silicon",                packingSize: "50",       uom: "nos" },
  { category: "BVG Products", productName: "Bvg Sanjeevani Pw.",         packingSize: "1",        uom: "kg" },
  { category: "BVG Products", productName: "Bvg Sanjeevani",             packingSize: "50",       uom: "ml" },
  { category: "BVG Products", productName: "Bvg Vardaan",                packingSize: "1.5",      uom: "kg" },
  { category: "BVG Products", productName: "Bvg Rajjo",                  packingSize: "600",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Dhara",                  packingSize: "150",      uom: "ml" },
  { category: "BVG Products", productName: "Bvg Jalsudhar Plus (In Inches)", packingSize: "3",   uom: "nos" },
  { category: "BVG Products", productName: "Bvg Solar Light Trap",       packingSize: "1",        uom: "nos" },
  { category: "BVG Products", productName: "Bvg Petrol Operated Spray Pump", packingSize: "1",   uom: "nos" },
  { category: "BVG Products", productName: "Bvg Krushi Tantradnyan Book", packingSize: "Marathi", uom: "nos" },
  { category: "BVG Products", productName: "Bvg Krushi Tantradnyan Book", packingSize: "Hindi",   uom: "nos" },
  { category: "BVG Products", productName: "Bvg Krushi Tantradnyan Book", packingSize: "English",  uom: "nos" },
  { category: "BVG Products", productName: "Bvg Agrosil Silica",         packingSize: "200",      uom: "gm" },
  { category: "BVG Products", productName: "Bvg Agrosil Silica",         packingSize: "40",       uom: "kg" },
  { category: "BVG Products", productName: "Bvg Mobile Auto Pro - Basic", packingSize: "1",       uom: "nos" },
  { category: "BVG Products", productName: "Bvg Mobile Auto Pro - With Battery", packingSize: "1", uom: "nos" },
  { category: "BVG Products", productName: "Bvg Dry Run Auto",           packingSize: "1",        uom: "nos" },
  { category: "BVG Products", productName: "Bvg Silspray (TTSC)",        packingSize: "1000",     uom: "ml" },

  // ── RAW MATERIAL ───────────────────────────────────────────────────────────
  { category: "Raw Material", productName: "Bvg Agro Safe DRUM",         packingSize: "200 Ltr",  uom: "drum" },
  { category: "Raw Material", productName: "Bvg Synergy (Lithovit Standard) BAG", packingSize: "1000 Kg", uom: "bag" },
  { category: "Raw Material", productName: "Bvg CalBoost + (Lithovit Boron 05) BAG", packingSize: "1000 Kg", uom: "bag" },
  { category: "Raw Material", productName: "Bvg Balancer Drum",          packingSize: "200 Ltr",  uom: "drum" },
  { category: "Raw Material", productName: "Bvg Stickwet Drum",          packingSize: "200 Ltr",  uom: "drum" },
  { category: "Raw Material", productName: "Bvg Root Care",              packingSize: "1",        uom: "nos" },
  { category: "Raw Material", productName: "Bvg Vardaan BAG",            packingSize: "25 Kg",    uom: "bag" },
  { category: "Raw Material", productName: "Bvg Rajjo BAG",              packingSize: "25 Kg",    uom: "bag" },
  { category: "Raw Material", productName: "Bvg Dhara",                  packingSize: "1",        uom: "nos" },
  { category: "Raw Material", productName: "Bvg Sanjeevani",             packingSize: "1",        uom: "nos" },
  { category: "Raw Material", productName: "Bvg Carbon Gr.",             packingSize: "1",        uom: "nos" },
  { category: "Raw Material", productName: "Biocoal Briquettes",         packingSize: "1",        uom: "nos" },

  // ── CONSUMABLES - EMPTY BAGS & POUCHES ─────────────────────────────────────
  { category: "Consumables - Empty Bags & Pouches", productName: "Empty Bags - Prom Pw.",    packingSize: "50 kg",   uom: "bag" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Empty Bags - Prom Gr.",    packingSize: "50 kg",   uom: "bag" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Empty Bags - Potash",      packingSize: "50 kg",   uom: "bag" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Empty Bags - Silicon",     packingSize: "50 Kg",   uom: "bag" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Empty Bags - Sanjeevani Pw.", packingSize: "50 kg", uom: "bag" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Empty Bags - Carbon Gr.",  packingSize: "10 kg",   uom: "bag" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Empty Bags - Carbon Gr.",  packingSize: "20 kg",   uom: "bag" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Sanjeevani Pouch",         packingSize: "1 Kg",    uom: "pouch" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Prom Pw. Pouch",           packingSize: "1 Kg",    uom: "pouch" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Synergy Pouch",            packingSize: "100 gm",  uom: "pouch" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Synergy Pouch",            packingSize: "250 gm",  uom: "pouch" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Synergy Pouch",            packingSize: "500 gm",  uom: "pouch" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Calboost Pouch",           packingSize: "250 GM",  uom: "pouch" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Calboost Pouch",           packingSize: "500 GM",  uom: "pouch" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Vardan Pouches",           packingSize: "1.5 Kg",  uom: "pouch" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Rajjo Pouches",            packingSize: "300 GM",  uom: "pouch" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Rajjo Pouches",            packingSize: "600 GM",  uom: "pouch" },
  { category: "Consumables - Empty Bags & Pouches", productName: "Cello Tape",               packingSize: "1",       uom: "roll" },
  { category: "Consumables - Empty Bags & Pouches", productName: "PVC Packing Patti (Straping Roll)", packingSize: "1", uom: "roll" },
];

export async function ensureSeeded() {
  const existing = await db.select().from(products);

  // Fresh database → insert everything in batches
  if (existing.length === 0) {
    const batchSize = 30;
    for (let i = 0; i < ALL_PRODUCTS.length; i += batchSize) {
      await db.insert(products).values(ALL_PRODUCTS.slice(i, i + batchSize));
    }
    return;
  }

  // Existing database → insert only the missing products (new categories)
  const existingKeys = new Set(
    existing.map(p => `${p.category}|${p.productName}|${p.packingSize}`)
  );
  const missing = ALL_PRODUCTS.filter(
    p => !existingKeys.has(`${p.category}|${p.productName}|${p.packingSize}`)
  );
  if (missing.length > 0) {
    const batchSize = 30;
    for (let i = 0; i < missing.length; i += batchSize) {
      await db.insert(products).values(missing.slice(i, i + batchSize));
    }
  }
}
